server:
  port: 8090
  servlet:
    context-path: /api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: sa
    password: sa
    url: jdbc:h2:mem:dbtest
    platform: h2
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    format-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.id.new_generator_mappings: false

logging:
  level:
    org.springframework: debug
#    org.hibernate: debug
wuxp:
  api:
    enabled-api-signature: true
