wuxp:
  picture:
    -simple:
      length: 6
      width: 200
      height: 80
    -test:
      length: 4
      width: 140
      height: 6
  env:
    jdbc-provider: com.wuxp.security.example.env.MyJdbcPropertyProvider
spring:
  profiles:
    active: local
  jackson:
    serialization:
      write-dates-as-timestamps: true

